DROP TABLE IF EXISTS USER;

CREATE TABLE USER(
 ID INT PRIMARY KEY,
 USERNAME VARCHAR(250),
 PASSWORD VARCHAR(250)
);
INSERT INTO USER VALUES(101, 'Spider Man', 'Web'), (103, 'Super Man', 'Fly');